---
- name: Install and configure Cockpit
  hosts: your_target_hosts
  become: true

  tasks:
    - name: Install Cockpit package
      package:
        name: cockpit
        state: present

    - name: Copy cockpit.conf.j2 to /etc/cockpit
      copy:
        src: cockpit.conf.j2
        dest: /etc/cockpit/cockpit.conf

    - name: Start and enable Cockpit service
      service:
        name: cockpit
        state: started
        enabled: true

    - name: Wait for port 9090 to be available
      wait_for:
        host: localhost
        port: 9090
        delay: 15
        timeout: 60
